package com.adnanearrassen.ytarchiver.python

import com.adnanearrassen.ytarchiver.domain.model.DownloadOptions
import com.adnanearrassen.ytarchiver.domain.model.Resolution
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/**
 * Translates the strongly-typed domain [DownloadOptions] into the flat JSON
 * shape that `yt_archiver.download()` expects. Centralising this keeps the
 * Python side dumb and the mapping auditable.
 */
object OptionsTranslator {

    fun toJson(options: DownloadOptions): JsonObject = when (options) {
        is DownloadOptions.Video -> buildJsonObject {
            put("type", "VIDEO")
            put("maxHeight", options.resolution.height.takeIf { it != Int.MAX_VALUE })
            put("fps", options.frameRate.fps)
            put("vcodecPrefix", options.videoCodec.ytdlpPrefix)
            put("acodecPrefix", options.audioCodec.ytdlpPrefix)
            put("container", options.container.ext)
            put("preferHdr", options.preferHdr)
            put("smartFallback", options.smartFallback)
            put("downloadSubtitles", options.downloadSubtitles)
            put("autoSubtitles", options.autoGeneratedSubtitles)
            put("embedSubtitles", options.embedSubtitles)
            put("subtitleLanguages", JsonArray(options.subtitleLanguages.map { JsonPrimitive(it) }))
            put("downloadThumbnail", options.downloadThumbnail)
            put("embedThumbnail", options.embedThumbnail)
            put("embedMetadata", options.embedMetadata)
            put("outputFileName", options.outputFileName)
        }

        is DownloadOptions.Music -> buildJsonObject {
            put("type", "MUSIC")
            put("format", options.format.ext)
            put("bitrateKbps", options.bitrate.kbps)
            put("sampleRateHz", options.sampleRate.hz)
            put("embedThumbnail", options.embedThumbnail)
            put("embedMetadata", options.embedMetadata)
            put("normalizeVolume", options.normalizeVolume)
            put("outputFileName", options.outputFileName)
        }
    }

    fun toJsonString(options: DownloadOptions): String = toJson(options).toString()
}
