package com.adnanearrassen.ytarchiver.domain.model

import kotlinx.serialization.Serializable

/**
 * Concrete, per-download choices. These are derived by merging the user's
 * default [AppSettings] with any per-download overrides from the Advanced
 * Options sheet, then handed to the Python layer which translates them into a
 * yt-dlp format selector + postprocessor chain.
 *
 * Serializable so the download queue can persist the exact options chosen and
 * the WorkManager worker can reconstruct them.
 */
@Serializable
sealed interface DownloadOptions {

    @Serializable
    data class Video(
        val resolution: Resolution = Resolution.P1080,
        val frameRate: FrameRate = FrameRate.ANY,
        val videoCodec: VideoCodec = VideoCodec.ANY,
        val audioCodec: VideoAudioCodec = VideoAudioCodec.ANY,
        val container: Container = Container.MP4,
        val preferHdr: Boolean = false,
        val smartFallback: Boolean = true,
        val downloadSubtitles: Boolean = false,
        val embedSubtitles: Boolean = false,
        val subtitleLanguages: List<String> = listOf("en"),
        val autoGeneratedSubtitles: Boolean = false,
        val downloadThumbnail: Boolean = true,
        val embedThumbnail: Boolean = true,
        val embedMetadata: Boolean = true,
        val outputFileName: String? = null,
        val outputFolder: String? = null,
    ) : DownloadOptions

    @Serializable
    data class Music(
        val format: AudioFormat = AudioFormat.MP3,
        val bitrate: AudioBitrate = AudioBitrate.K256,
        val sampleRate: SampleRate = SampleRate.SOURCE,
        val embedThumbnail: Boolean = true,
        val embedMetadata: Boolean = true,
        val normalizeVolume: Boolean = false,
        val outputFileName: String? = null,
        val outputFolder: String? = null,
    ) : DownloadOptions

    val type: DownloadType
        get() = when (this) {
            is Video -> DownloadType.VIDEO
            is Music -> DownloadType.MUSIC
        }
}
