package com.adnanearrassen.ytarchiver.domain.model

/**
 * Result of analysing a URL with yt-dlp (`extract_info`, download=False).
 * Represents either a single media item or a playlist of them.
 */
data class MediaInfo(
    val id: String,
    val url: String,
    val title: String,
    val uploader: String?,
    val channelUrl: String?,
    val durationSeconds: Long?,
    val thumbnailUrl: String?,
    val description: String?,
    val viewCount: Long?,
    val uploadDate: String?,
    val isLive: Boolean = false,
    val kind: MediaKind = MediaKind.VIDEO,
    val videoFormats: List<VideoFormat> = emptyList(),
    val audioFormats: List<AudioFormat2> = emptyList(),
    val subtitles: List<SubtitleTrack> = emptyList(),
    /** Non-null when the URL resolved to a playlist. */
    val playlist: PlaylistInfo? = null,
) {
    val isPlaylist: Boolean get() = playlist != null
}

/** A yt-dlp video-bearing format. */
data class VideoFormat(
    val formatId: String,
    val ext: String,
    val height: Int?,
    val width: Int?,
    val fps: Int?,
    val vcodec: String?,
    val acodec: String?,
    val fileSizeBytes: Long?,
    val tbrKbps: Double?,
    val isHdr: Boolean = false,
) {
    val qualityLabel: String
        get() = buildString {
            append(height?.let { "${it}p" } ?: ext)
            if (fps != null && fps >= 50) append(fps)
            if (isHdr) append(" HDR")
        }
}

/** A yt-dlp audio-only format. Named AudioFormat2 to avoid clashing with the
 *  [AudioFormat] output-format enum. */
data class AudioFormat2(
    val formatId: String,
    val ext: String,
    val acodec: String?,
    val abrKbps: Double?,
    val asrHz: Int?,
    val fileSizeBytes: Long?,
) {
    val qualityLabel: String
        get() = buildString {
            append(acodec ?: ext)
            abrKbps?.let { append(" · ${it.toInt()} kbps") }
        }
}

data class SubtitleTrack(
    val languageCode: String,
    val languageName: String,
    val isAutoGenerated: Boolean,
)

data class PlaylistInfo(
    val id: String,
    val title: String,
    val uploader: String?,
    val itemCount: Int,
    val entries: List<PlaylistEntry>,
)

data class PlaylistEntry(
    val id: String,
    val url: String,
    val title: String,
    val durationSeconds: Long?,
    val thumbnailUrl: String?,
)
