package com.adnanearrassen.ytarchiver.python.dto

import com.adnanearrassen.ytarchiver.domain.model.AudioFormat2
import com.adnanearrassen.ytarchiver.domain.model.MediaInfo
import com.adnanearrassen.ytarchiver.domain.model.MediaKind
import com.adnanearrassen.ytarchiver.domain.model.PlaylistEntry
import com.adnanearrassen.ytarchiver.domain.model.PlaylistInfo
import com.adnanearrassen.ytarchiver.domain.model.SubtitleTrack
import com.adnanearrassen.ytarchiver.domain.model.VideoFormat
import kotlinx.serialization.Serializable

/** JSON mirror of what `yt_archiver.analyze()` returns. */
@Serializable
data class AnalyzeDto(
    val error: String? = null,
    val id: String = "",
    val url: String = "",
    val title: String = "",
    val uploader: String? = null,
    val channelUrl: String? = null,
    val durationSeconds: Long? = null,
    val thumbnailUrl: String? = null,
    val description: String? = null,
    val viewCount: Long? = null,
    val uploadDate: String? = null,
    val isLive: Boolean = false,
    val kind: String = "VIDEO",
    val videoFormats: List<VideoFormatDto> = emptyList(),
    val audioFormats: List<AudioFormatDto> = emptyList(),
    val subtitles: List<SubtitleDto> = emptyList(),
    val playlist: PlaylistDto? = null,
)

@Serializable
data class VideoFormatDto(
    val formatId: String = "",
    val ext: String = "",
    val height: Int? = null,
    val width: Int? = null,
    val fps: Int? = null,
    val vcodec: String? = null,
    val acodec: String? = null,
    val fileSizeBytes: Long? = null,
    val tbrKbps: Double? = null,
    val isHdr: Boolean = false,
)

@Serializable
data class AudioFormatDto(
    val formatId: String = "",
    val ext: String = "",
    val acodec: String? = null,
    val abrKbps: Double? = null,
    val asrHz: Int? = null,
    val fileSizeBytes: Long? = null,
)

@Serializable
data class SubtitleDto(
    val languageCode: String = "",
    val languageName: String = "",
    val isAutoGenerated: Boolean = false,
)

@Serializable
data class PlaylistDto(
    val id: String = "",
    val title: String = "",
    val uploader: String? = null,
    val itemCount: Int = 0,
    val entries: List<PlaylistEntryDto> = emptyList(),
)

@Serializable
data class PlaylistEntryDto(
    val id: String = "",
    val url: String = "",
    val title: String = "",
    val durationSeconds: Long? = null,
    val thumbnailUrl: String? = null,
)

fun AnalyzeDto.toDomain(): MediaInfo = MediaInfo(
    id = id,
    url = url,
    title = title,
    uploader = uploader,
    channelUrl = channelUrl,
    durationSeconds = durationSeconds,
    thumbnailUrl = thumbnailUrl,
    description = description,
    viewCount = viewCount,
    uploadDate = uploadDate,
    isLive = isLive,
    kind = runCatching { MediaKind.valueOf(kind) }.getOrDefault(MediaKind.VIDEO),
    videoFormats = videoFormats.map {
        VideoFormat(
            formatId = it.formatId, ext = it.ext, height = it.height, width = it.width,
            fps = it.fps, vcodec = it.vcodec, acodec = it.acodec,
            fileSizeBytes = it.fileSizeBytes, tbrKbps = it.tbrKbps, isHdr = it.isHdr,
        )
    },
    audioFormats = audioFormats.map {
        AudioFormat2(
            formatId = it.formatId, ext = it.ext, acodec = it.acodec,
            abrKbps = it.abrKbps, asrHz = it.asrHz, fileSizeBytes = it.fileSizeBytes,
        )
    },
    subtitles = subtitles.map {
        SubtitleTrack(it.languageCode, it.languageName, it.isAutoGenerated)
    },
    playlist = playlist?.let { p ->
        PlaylistInfo(
            id = p.id, title = p.title, uploader = p.uploader, itemCount = p.itemCount,
            entries = p.entries.map { e ->
                PlaylistEntry(e.id, e.url, e.title, e.durationSeconds, e.thumbnailUrl)
            },
        )
    },
)
